name:                programming-in-haskell
version:             0.1.0.0
license:             BSD3

dependencies:
- base == 4.*

library:
  source-dirs: src

executables:
  programming-in-haskell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - programming-in-haskell
