name:                programming-in-haskell
version:             0.1.0.0
license:             BSD3

ghc-options: -Wall

dependencies:
- base == 4.*

library:
  source-dirs: src

executable:
  main:                Main.hs
  source-dirs:         app
  dependencies:
  - programming-in-haskell
